# baseURL: 'http://localhost:1313'
languageCode: 'zh-cn'
title: "小电动的大电池"
theme: 'hugo-theme-tokiwa'

author: Billy Yang
copyright: '<p xmlns:cc="https://creativecommons.org/ns#" >Copyright © 2023 Billy Yang.<br>Contents licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-NC-SA 4.0</a></p>'

hasCJKLanguage: true

params:
  math: true
  fuse: true
  useChineseFonts: true
  description: "小电动的个人博客（正在建设中）"
  outputs:
    home: ["HTML", "JSON", "RSS"]

taxonomies:
  category: "categories"
  tag: "tags"
  series: "series"

social:
  github: "https://github.com/handsomexdd1024"
  mail: "mailto:handsomexdd1024@gmail.com"

menus:
  main:
  - name: 关于我
    url: /about/
    weight: 3
  - name: 标签
    url: /tags/
    weight: 1
  - name: 分类
    url: /categories/
    weight: 1
  - name: 系列
    url: /series/
    weight: 1
  - name: 全部文章
    # identifier: posts
    url: /posts/
    weight: 2
  - name: 友情链接
    url: /friends/
    weight: 4


